### ISSUE TITLE
[코드수정] 변수 두번 선언

### ISSUE THREAD

**Issue by jiyoung211** [Hyeon9mak/assignment2#16]
main.c 파일에서
전역변수로 struct tm *time1, *time2;가 선언되어 있는데 
void filetime2(void) 함수에서 struct tm* time; 변수를 또 선언했네요
수정해주세요 ^^

**Comment by pdache** [comment]
아아! 제 담당 함수에서 실수가 나왔군요^__^
시정하겠어욧!
