### ISSUE TITLE
7, 8번 함수에서 올바른 용어로 정정해주시기 바랍니다 ^^

### ISSUE THREAD

**Issue by pdache** [Hyeon9mak/assignment2#23]
`
//두 개의 파일 수정 날짜를 비교하는 함수 작성
void datecmp(void)
{
	printf("Date Compare\n");

	if(time1->tm_mon == time2->tm_mon){
		if(time1->tm_mday > time2->tm_mday)
			printf("Text1 is bigger\n");
			else
			printf("Text2 is bigger\n");
		}
	else if(time1->tm_mon > time2->tm_mon)
		printf("Text 1 is bigger\n");
		else printf("Text2 is bigger\n");
}

//두 개의 파일 수정 시간을 비교하는 함수 작성
void timecmp(void)
{
	printf("time Compare\n");

	if(time1->tm_hour == time2->tm_hour){
		if(time1->tm_min > time2->tm_min)
			printf("Text1 is bigger\n");
			else
			printf("Text2 is bigger\n");
		}
	else if(time1->tm_hour > time2->tm_hour)
		printf("Text 1 is bigger\n");
		else printf("Text2 is bigger\n");
}`

위의 코드에서 시간을 비교하는 건데 bigger이라는 용어는 적절치 않은 것 같네요..^^

**Comment by wogns7534** [comment]
빨리 해주세여.
